export {
    IconArrowLeft,
    IconArrowRight,
    IconArrowUp,
    IconSend,
    IconBook,
    IconMail,
    IconLock,
    IconUser,
    IconMessage,
    IconEdit,
    IconTrash,
    IconDotsVertical,
    IconPlus,
    IconFilter,
    IconX,
    IconSearch,
    IconMoodSmile,
    IconFlame,
    IconCheck,
    IconCalendarStats,
    IconNotebook,
    IconHome,
    IconPlayerPlay,
    IconPlayerPause,
    IconVolume,
    IconVolumeOff,
  } from '@tabler/icons-react'
  