export {
    IconArrowLeft,
    IconArrowRight,
    IconArrowUp,
    IconSend,
    IconChevronLeft, 
    IconChevronRight,
    IconPlayerPlay, 
    IconVolume, 
    IconClock,
    IconBrandGithub, 
    IconBrandLinkedin,
    IconMoodHappy,
    IconMail,
    IconBook,
    IconLock,
    IconUser,
    IconMessage,
    IconEdit,
    IconTrash,
    IconDotsVertical,
    IconPlus,
    IconFilter,
    IconX,
    IconSearch,
    IconMoodSmile,
    IconFlame,
    IconCheck,
    IconCalendarStats,
    IconNotebook,
    IconHome,
    IconPlayerPause,
    IconVolumeOff,
  } from '@tabler/icons-react'
  